### ISSUE TITLE
Empty file in emulator but works on Real device...

### ISSUE THREAD

**Issue by ajosecueto** [sbis04/video_trimmer#94] opened 2021-03-10 22:55 UTC
Pixel #3XL API 30
Flutter 2

Future<String> _saveVideo() async {
    setState(() {
      _progressVisibility = true;
    });

    String _value;

    await widget._trimmer
        .saveTrimmedVideo(startValue: _startValue, endValue: _endValue)
        .then((value) {
      setState(() {
        _progressVisibility = false;
        _value = value;
      });
    });

    return _value;
  }

In emulator doesnt works but in real device works perfectly

**Comment by Gicminos** [comment] 2021-03-14 19:30
Similar issue happens to me. While using it on the emulator, the file returned is 0 bytes size and I can see in the console this ffmpeg error:
`[mp4 @ 0x7a3b935c10] Could not find tag for codec amr_nb in stream #1, codec not currently supported in container`

The thing that worries me are if there are real devices with that codec that might cause issues. Here the problem is not about making the library work on emulator but about detecting the trimming issues and throw a related error.

**Comment by ajosecueto** [comment] 2021-03-14 19:34
@Gicminos I think you can try to deploy in many devices as posible and try to catch that error using sentry or another error Handling Platform.

I will release an app in few days. I will share information about with you.

**Comment by ajosecueto** [comment] 2021-03-20 15:36
So i was testing in few devices and in Samsung devices video trimmer doesn't save the file...the plugging doesn't work.

path saved is null... in emulator API 30 and Samsung real devices
#

@sbis04

**Comment by sbis04** [comment] 2021-04-09 13:29
@ajosecueto @Gicminos Can you please try with the latest version `0.4.0`, and let me know?

**Comment by sbis04** [comment] 2021-05-22 17:23
Closing this assuming it to be solved. Feel free to open if the issue persists.

**Closed by sbis04** 2021-05-22 17:23 UTC
Labels: bug

**Comment by themadmrj** [comment] 2021-05-31 17:25
I just tested this on a real device and the issue still exists on iOS.
