### ISSUE TITLE
Set max duration of the video

### ISSUE THREAD

**Issue by saurabhunify** [sbis04/video_trimmer#39] opened 2020-07-29 09:41 UTC
I am using the video_trimmer for my project. I want to trim the video to maximum 15 secs. By default whenever I select any video it is selected as whole, for example if I select a video of 60 secs the default selected video covers all 60 secs. But I want that even if the source video is a length greater than 15 secs it should select only 15 seconds from the start like the video trimmer in whatsapp which only selects 30 seconds of the video while uploading a video status.
Thanks in advance if you can provide some argument for max length to be selected  in TrimEditor class

**Comment by sbis04** [comment] 2020-08-04 09:11
Duplicate of: #4

**Closed by sbis04** 2020-08-04 09:11 UTC
