### ISSUE TITLE
App size increased heavily

### ISSUE THREAD

**Issue by avvari-da** [sbis04/video_trimmer#32] opened 2020-07-02 05:51 UTC
This is a great plugin, but my app bundle size increased by about 40 mb after adding this package.

Is there a way to reduce this? Or is it something I can't avoid?

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2020.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
</details>

**Comment by wilfredonoyola** [comment] 2020-07-02 14:44
@dheeraj2dj I think this was added for the package "[flutter_ffmpeg](https://pub.dev/packages/flutter_ffmpeg)" because the video_trimmer use flutter_ffmpeg as manager the video editor.

But, I think is not posible reduce the size for your app while use the package flutter_ffmpeg.

Let me know your thoughts @sbis04

**Comment by leochiu-work** [comment] 2020-07-04 02:14
For the flutter_ffmpeg packages listed here https://github.com/sbis04/video_trimmer#ffmpeg-release

Will the plugin still working if we use min-lts? And will the app size smaller as well?
Currently I am using full-lts.

**Comment by dheeraj2dj** [comment] 2020-07-04 06:42
@leochiu-work I was using `min-gpl-lts`, still the huge size. Will try `min-lts`

**Comment by masfour7** [comment] 2020-09-09 12:56
@dheeraj2dj Have you tried using the min-lts?

**Comment by dheeraj2dj** [comment] 2020-09-09 13:35
@masfour7 yea, but no advantage. Reduced just 1-2 mb

**Comment by themadmrj** [comment] 2020-11-04 14:32
There are already existing native libraries doing the heavy lifting. I could write an Android plugin within 2 weeks, but don't have any iOS knowledge. If someone can write the iOS counter part, we could setup a native lib to avoid using ffmpeg. There is no other solution to the size problem.

**Comment by pooja96km** [comment] 2021-02-12 10:26
Has anyone found the solution?

**Comment by themadmrj** [comment] 2021-02-12 10:36
> Has anyone found the solution?

Still hoping someone can write the iOS part ^^

**Comment by pooja96km** [comment] 2021-02-12 10:43
> > Has anyone found the solution?
> 
> Still hoping someone can write the iOS part ^^
Have you written for android?

**Comment by themadmrj** [comment] 2021-02-12 10:54
Not yet, but can do it quickly. But useless for a flutter app without iOS, so I'm waiting for someone that can do that before I start.

**Comment by pooja96km** [comment] 2021-02-12 11:04
> Not yet, but can do it quickly. But useless for a flutter app without iOS, so I'm waiting for someone that can do that before I start.

Ok

**Comment by ArjanAswal** [comment] 2021-02-18 04:58
> > Has anyone found the solution?
> 
> Still hoping someone can write the iOS part ^^

@themadmrj I recommend that you go ahead with an android-only implementation. People will certainly start to contribute to your repo as your plugin starts picking up the pace, and someone will come up with an implementation for iOS.

**Comment by themadmrj** [comment] 2021-02-18 06:10
> > > Has anyone found the solution?
> > 
> > 
> > Still hoping someone can write the iOS part ^^
> 
> @themadmrj I recommend that you go ahead with an android-only implementation. People will certainly start to contribute to your repo as your plugin starts picking up the pace, and someone will come up with an implementation for iOS.

Not so sure about that. Without external reference like an article on Medium, a repo lacks visibility and may not get contribution. For instance, I wrote a chat UI library because dashchat is inactive, which is a lot more complete, and yet it doesn't really pick up the pace! If someone would just commit with me, that would certainly give me the push. The problem is, even if I write an android only lib, I can't use it myself unless it cover both platforms xD

**Comment by aliaktas-tr** [comment] 2022-04-28 14:24
Did anyone find any solition?

**Comment by sbis04** [comment] 2022-10-30 02:22
Closing this issue because there have been a few changes to the `ffmpeg_kit_flutter`. Please open a new issue if you want to discuss this further.

**Closed by sbis04** 2022-10-30 02:22 UTC
