### ISSUE TITLE
startValue is ignored when saving trimmed video in mp4 format

### ISSUE THREAD

**Issue by hanswang0608** [sbis04/video_trimmer#100] opened 2021-04-08 18:06 UTC
Here is the code I'm calling.
```
final savedPath = await trimmer.saveTrimmedVideo(
      startValue: _startValue,
      endValue: _endValue,
      outputFormat: FileFormat.mp4,
      storageDir: StorageDir.temporaryDirectory,
      videoFileName: 'trimmed_video',
);
```

The field startValue has no effect on the output, while endValue works as expected.
Changing format to gif instead of mp4 produces correct output but I need the output as mp4.

**Comment by sbis04** [comment] 2021-04-09 13:38
Closing this as it is a duplicate of #85 , please continue the conversation there.

**Closed by sbis04** 2021-04-09 13:38 UTC
Labels: bug
