### ISSUE TITLE
Not able to set max video duration

### ISSUE THREAD

**Issue by saurabhrayakwar** [sbis04/video_trimmer#27] opened 2020-06-18 13:47 UTC
Steps to reproduce - 

1. Use imagepicker.pickVideo to select video from file manager
2. video_player plays the video successfully
3. Use trimmer to trim the picked video
4. Save the trimmed video
5. imagepicker.pickVideo the trimmed video to select the trimmed video now

Observation - 

1.  Trimmed video is not initialisating and is not playable in the [video_player](https://pub.dev/packages/video_player).

Code to save the video -
```
await widget._trimmer
        .saveTrimmedVideo(
            startValue: _startValue,
            endValue: _endValue,
            outputFormat: FileFormat.mp4,
            videoFileName: 'Trimmed_${new DateTime.now()}',
            videoFolderName: "Videos/Trimmed",
            storageDir: StorageDir.externalStorageDirectory)
        .then((value) {
      setState(() {
        _progressVisibility = false;
        _value = value;
      });
    });
```

Please let me know if you need more details on reproducing this issue?
Thanks!

**Comment by saurabhrayakwar** [comment] 2020-06-18 13:49
@sbis04

**Comment by saurabhrayakwar** [comment] 2020-06-18 14:18
This could be related - https://stackoverflow.com/questions/48356188/flutter-video-player-not-playing-video-saved-to-application-directory

**Comment by saurabhrayakwar** [comment] 2020-06-18 14:51
Actually I figured out the reason after a bit of manual testing. If I trim the video to less than 1s and between 0s & 1s, the duration of the video shows up as zero in the Android File manager and hence the video player is unable to initialise that particular video.

**Comment by saurabhrayakwar** [comment] 2020-06-18 20:29
@sbis04  Is there a way to figure out `Duration` of the video after trimming ?

**Comment by sbis04** [comment] 2020-06-19 02:06
Hi @saurabhrayakwar, currently there is no way to set the maximum trimmed video duration. I know this is a really important feature and is currently in development. However, you are open to submit PR.

**Comment by sbis04** [comment] 2020-06-19 02:10
Closing this issue as there is already an issue regarding this.

Duplicate of: #4

**Closed by sbis04** 2020-06-19 02:10 UTC
