### ISSUE TITLE
Error on TrimEditor

### ISSUE THREAD

**Issue by RubenPain** [sbis04/video_trimmer#88] opened 2021-03-05 14:37 UTC
I get this error on my `TrimEditor()` widget, I get the start of my video and after at one moment I get this error just on this widget when I scroll.

`flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building:
flutter: 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 927 pos 14: 'bytes !=
flutter: null': is not true.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new MemoryImage (package:flutter/src/painting/image_provider.dart:927:14)
flutter: #3      ThumbnailViewer.build.<anonymous closure>.<anonymous closure> (package:video_trimmer/src/thumbnail_viewer.dart:66:28)
flutter: #4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
flutter: #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1201:28)
flutter: #6      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1145:67)
flutter: #7      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1192:23)
flutter: #8      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1124:7)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
flutter: #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5503:32)
flutter: #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6105:17)
flutter: #18     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:228:11)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
flutter: #29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
flutter: #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
flutter: #37     ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
flutter: #42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
flutter: #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
flutter: #48     StatelessElement.update (package:flutter/src/widgets/framework.dart:4576:5)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
flutter: #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
flutter: #51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
flutter: #53     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694:33)
flutter: #54     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:873:21)
flutter: #55     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
flutter: #56     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #57     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter: #58     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter: #62     _invoke (dart:ui/hooks.dart:161:10)
flutter: #63     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
flutter: #64     _drawFrame (dart:ui/hooks.dart:120:31)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════`

If you have some good tips or an answer please.

**Comment by ArjanAswal** [comment] 2021-03-05 14:53
Can you post the code?

**Comment by sbis04** [comment] 2021-04-09 13:32
Closing this as it is a duplicate of #94 , please continue the conversation there.

**Closed by sbis04** 2021-04-09 13:32 UTC
