### ISSUE TITLE
TrimEditor error: 'bytes != null': is not true

### ISSUE THREAD

**Issue by janlektonen** [sbis04/video_trimmer#95] opened 2021-03-12 08:09 UTC
Hi -nice package.

I get this error when opening videoTrimmer with a mp4 videofile. Al thumbnails are rendered except the last few ones, then this error comes?

Sometimes the file load fine and all thumbnails are shown. But often this error comes... I made sure the file is loaded before opening TrimEditor()

I can see that issue #88 mentioned the same error... 

═══════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building:
'package:flutter/src/painting/image_provider.dart': Failed assertion: line 928 pos 14: 'bytes != null': is not true.

When the exception was thrown, this was the stack
#2      new MemoryImage
package:flutter/…/painting/image_provider.dart:928
#3      ThumbnailViewer.build.<anonymous closure>.<anonymous closure>
package:video_trimmer/src/thumbnail_viewer.dart:66
#4      SliverChildBuilderDelegate.build
package:flutter/…/widgets/sliver.dart:449
#5      SliverMultiBoxAdaptorElement._build
package:flutter/…/widgets/sliver.dart:1130
#6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
package:flutter/…/widgets/sliver.dart:1143
...

**Comment by pictureframing** [comment] 2021-03-18 09:01
Same problem

**Comment by ajosecueto** [comment] 2021-03-23 21:10
#94 the error occurs when VideoThumbnail is trying to create from a empty file or null path... works i'm some devices but no in emulator and samsung devices for example...

package mantainer doesnt track issues, i posted it 13 days ago, without response...

**Comment by sbis04** [comment] 2021-04-09 13:31
Closing this as it is a duplicate of #94 , please continue the conversation there.

**Closed by sbis04** 2021-04-09 13:31 UTC
