### ISSUE TITLE
Load list of video files

### ISSUE THREAD

**Issue by kameshkarthi** [sbis04/video_trimmer#7] opened 2020-05-12 13:34 UTC
Hello sir, How can i load list of video files??
Good Job!!!

**Comment by sbis04** [comment] 2020-05-13 07:12
I didn't quite understand your question. Why do you want to load multiple video files for trimming?

Do you want to trim multiple files at the same time? I don't think it is a good decision to do that.

If you still want to achieve that kind of functionality, then you can try to use this package or modify it as per your need.

**Comment by kameshkarthi** [comment] 2020-05-13 07:21
if i want share videos after trimming like whats app, then how can i do that??

**Comment by sbis04** [comment] 2020-05-13 12:14
You can access the file by its **path** and then you can perform any operation upon it.

**Comment by kameshkarthi** [comment] 2020-05-14 02:56
I did it by passing the video file in trimmer.loadvideo() function instead of selecting from gallery..
Thank you so much sir....

**Comment by sbis04** [comment] 2020-05-14 06:46
Great! Closing this as the issue is fixed.

**Closed by sbis04** 2020-05-14 06:46 UTC
