### ISSUE TITLE
App size increased drastically when I used video_trimmer

### ISSUE THREAD

**Issue by vishal-jadhao** [sbis04/video_trimmer#86] opened 2021-03-01 05:34 UTC
Hi @sbis04 @ArjanAswal ,

I find this very good package, but got size related issue. please help.

Before adding video_trimmer app size was around 12mb and when added 

min ----> app size is 78mb
video ----> 160mb

Above size is of Release builds.

**Comment by ArjanAswal** [comment] 2021-03-01 12:00
> Hi @sbis04 @ArjanAswal ,
> 
> I find this very good package, but got size related issue. please help.
> 
> Before adding video_trimmer app size was around 12mb and when added 
> 
> min ----> app size is 78mb
> video ----> 160mb
> 
> Above size is of Release builds.

Unfortunately nothing can be done about it as the plugin requires ffmpeg library which is quite heavy.
Make sure to obfuscate your release build as it reduces the app size significantly.
Also use `min-lts`.

**Comment by sbis04** [comment] 2021-04-09 13:37
Closing this as it is a duplicate of #32 , please continue the conversation there.

**Closed by sbis04** 2021-04-09 13:37 UTC
