### ISSUE TITLE
Zoom time axis, when the video is lengthy

### ISSUE THREAD

**Issue by JamesBondPc** [sbis04/video_trimmer#52] opened 2020-09-10 06:37 UTC
How to zoom this time axis, when the time axis is very long, zooming changes the width, it takes a long time to load images

**Comment by sbis04** [comment] 2020-10-10 03:51
I am thinking of an implementation of this. It will soon be available in the package.

Closing the duplicate of this issue: #48

**Comment by JamesBondPc** [comment] 2020-10-26 06:23
> I am thinking of an implementation of this. It will soon be available in the package.
> 
> Closing the duplicate of this issue: #48

When will this function be available ？

**Comment by JamesBondPc** [comment] 2020-11-05 10:30
Almost a month has passed and this feature has not been added yet. Is it because no one maintains it?

**Comment by sbis04** [comment] 2020-12-07 12:49
@JamesBondPc I know this feature hasn't been implemented for a long time. Actually, I am really busy with some other work, so I was not finding much time to maintain it. Though I will try to add some of the enhancements by the end of December.

**Closed** 2022-10-29 15:39 UTC
Labels: enhancement, in development
